### ISSUE TITLE
Create Folder in AMP_AD

### ISSUE THREAD

**Issue by andrewelamb** [Sage-Bionetworks/projectlive_AMP_AD#1]
Please create a folder in AMP_AD where I and whoever will be updating the data files monthly have edit permissions.

**Comment by pitviper6** [comment]
Done! https://www.synapse.org/#!Synapse:syn26076785

**Comment by andrewelamb** [comment]
@pitviper6 I need edit permissions for this folder. Thanks!

**Comment by pitviper6** [comment]
@andrewelamb oops, sorry about that! You have edit permissions now.
